export const AUTH_STACK = "AUTH_STACK";
export const TAB_STACK = "TAB_STACK";

export const TAB_STACK_MAIN = "TAB_STACK_MAIN";

export const AUTH_STACK_MAIN = "AUTH_STACK_MAIN";
export const AUTH_STACK_CONFIRM = "AUTH_STACK_CONFIRM";

export const MAIN_STACK_MAIN = "MAIN_STACK_MAIN";
export const MAIN_STACK_ABOUT = "MAIN_STACK_ABOUT";
